name: Hannes
favicon: null
layout_spectrum: 0.46392
typography_spectrum: 0.48571
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#6a3412'
    - '#ab5024'
    - '#4c753d'
    - '#c1a073'
  brandStrength: 1
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 1
purpose: []
