analytics: {}
color:
  brandColors:
    - '#CDCD9C'
    - '#5A6229'
    - '#8B9462'
    - '#E64131'
    - '#EE6A52'
  brandStrength: 0.7875
  lightness: 0.446875
  rhythmicContrast: 0.634375
  saturation: 0.209375
cta: {}
layout_spectrum: 0.382812
name: Hannes
opengraph: {}
purpose:
  - {}
typography_spectrum: 0.789772
