typography_spectrum: 1
color:
  brandColors:
    - '#001D1F'
    - '#E6D3AB'
    - '#FDFDFD'
    - '#BEAF88'
    - '#2F5D5D'
  brandStrength: 0
  lightness: 0.495614
  rhythmicContrast: 0
  saturation: 0.375
opengraph: {}
layout_spectrum: 0.92919
analytics: {}
name: Hannes
cta: {}
style: the-composer
navigation:
  - name: Coffee & Space
    url: 'http://coffeeandspace.com'
    type: external
purpose:
  - {}
