name: null
favicon: null
layout_spectrum: 0
typography_spectrum: 0.46409
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#b6e5f5'
    - '#9b9a95'
    - '#f7ffff'
    - '#664939'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
