analytics: {}
color:
  brandColors:
    - '#c8c7c5'
    - '#656668'
    - '#2a2e2f'
    - '#a31513'
    - '#fdfefe'
  brandStrength: 1
  lightness: 0.496875
  rhythmicContrast: 0
  saturation: 0.498437
cta: {}
name: Hannes
opengraph: {}
purpose: {}
