name: Hannes
favicon: null
layout_spectrum: 0.25248
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#CDCD9C'
    - '#5A6229'
    - '#8B9462'
    - '#E64131'
    - '#EE6A52'
  brandStrength: 0.275
  lightness: 0.259375
  saturation: 0.781531
  rhythmicContrast: 0.526562
purpose:
  - name: null
    item: null
    url: null
