name: Hannes
layout_spectrum: 0.92919
typography_spectrum: 1
cta: {}
analytics: {}
opengraph: {}
color:
  brandColors:
    - '#001D1F'
    - '#E6D3AB'
    - '#FDFDFD'
    - '#BEAF88'
    - '#2F5D5D'
  brandStrength: 0
  lightness: 0.495614
  saturation: 0.375
  rhythmicContrast: 0
purpose:
  - {}
style: the-composer
navigation:
  - name: My main website?
    url: 'http://hannesstruss.de'
    type: external
  - name: My other drawings website
    url: 'http://hannesstruss.de/zeichnungen'
    type: external
  - name: Wahnsinn
    url: 'http://nice.cool'
    type: external
  - name: a
    url: a
    type: external
  - name: b
    url: b
    type: external
  - name: c
    url: c
    type: external
  - name: e
    url: e
    type: external
