typography_spectrum: 1
color:
  brandColors:
    - '#001D1F'
    - '#E6D3AB'
    - '#FDFDFD'
    - '#BEAF88'
    - '#2F5D5D'
  brandStrength: 0
  lightness: 0.495614
  saturation: 0.375
  rhythmicContrast: 0
opengraph: {}
layout_spectrum: 0.92919
analytics: {}
name: Hannes
cta: {}
style: the-composer
navigation:
  - name: f
    url: f
    type: external
  - name: xjxjxjxjd
    url: dhdhd
    type: external
  - name: h
    url: h
    type: external
  - name: bbb
    url: gvb
    type: external
purpose:
  - {}
