name: Hannes
layout_spectrum: 0.92919
typography_spectrum: 1
cta: {}
analytics: {}
opengraph: {}
color:
  brandColors:
    - '#001D1F'
    - '#E6D3AB'
    - '#FDFDFD'
    - '#BEAF88'
    - '#2F5D5D'
  brandStrength: 0
  lightness: 0.495614
  saturation: 0.375
  rhythmicContrast: 0
purpose:
  - {}
style: the-composer
navigation:
  - name: a
    url: a
    type: external
  - name: b
    url: b
    type: external
  - name: e
    url: e
    type: external
  - name: ''
    id: 7438a728-6c94-4856-8d73-f0a50b267fac
    type: content
  - name: c
    url: c
    type: external
  - name: xnxnx
    id: 1cf4d8c7-2d98-4293-907d-d7ddd17b2aa0
    type: content
  - name: f
    url: f
    type: external
  - name: toll
    id: 1cf4d8c7-2d98-4293-907d-d7ddd17b2aa0
    type: content
  - name: xjxjxjxjd
    url: dhdhd
    type: external
  - name: cooooool
    id: 7438a728-6c94-4856-8d73-f0a50b267fac
    type: content
  - name: h
    url: h
    type: external
  - name: bbb
    url: gvb
    type: external
  - name: bjbfg
    id: 1cf4d8c7-2d98-4293-907d-d7ddd17b2aa0
    type: content
