name: Hannes
favicon: null
layout_spectrum: 0.65646
typography_spectrum: 0.400337
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#BDBDBD'
    - '#101829'
    - '#AC627B'
    - '#486BB7'
    - '#000000'
  brandStrength: 0.385135
  lightness: 0.178125
  saturation: 0.758445
  rhythmicContrast: 0.820945
purpose:
  - name: null
    item: null
    url: null
