analytics: {}
color:
  brandColors:
    - '#B4AC83'
    - '#5A542A'
    - '#9C9473'
    - '#CDC594'
    - '#FFF6AC'
  brandStrength: 0.657812
  lightness: 0.259375
  rhythmicContrast: 0.526562
  saturation: 0.781531
cta: {}
layout_spectrum: 0.8
name: Hannes
opengraph: {}
purpose:
  - {}
