name: Hannes
favicon: null
layout_spectrum: 0.8
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e59e8c'
    - '#080705'
    - '#c67759'
    - '#676966'
    - '#7b3c2d'
  brandStrength: 1
  lightness: 0.953828
  saturation: 0.781531
  rhythmicContrast: 0.19375
purpose:
  - name: null
    item: null
    url: null
