name: Hannes
favicon: null
layout_spectrum: 0.24742
typography_spectrum: 0.41561
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c8c7c5'
    - '#656668'
    - '#2a2e2f'
    - '#a31513'
    - '#fdfefe'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
