analytics: {}
color:
  brandColors:
    - '#c2d6d7'
    - '#697d7b'
    - '#da6600'
    - '#920010'
    - '#181918'
  brandStrength: 0
  lightness: 0.5625
  rhythmicContrast: 0
  saturation: 0.375
cta: {}
layout_spectrum: 0.92919
name: Hannes
opengraph: {}
purpose:
  - {}
typography_spectrum: 0.065104
