name: Hannes
favicon: null
layout_spectrum: 0.65646
typography_spectrum: 0.400337
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#BDBDBD'
    - '#101829'
    - '#AC627B'
    - '#486BB7'
    - '#000000'
  brandStrength: 0
  lightness: 0.25
  saturation: 0.375
  rhythmicContrast: 0
purpose:
  - name: null
    item: null
    url: null
