analytics: {}
color:
  brandColors:
    - '#CDCD9C'
    - '#5A6229'
    - '#8B9462'
    - '#E64131'
    - '#EE6A52'
  brandStrength: 0.275
  lightness: 0.259375
  rhythmicContrast: 0.526562
  saturation: 0.781531
cta: {}
layout_spectrum: 0.1765957
name: Hannes
opengraph: {}
purpose:
  - {}
typography_spectrum: 0.789772
