name: Hannes
favicon: null
layout_spectrum: 0.92919
typography_spectrum: 0.400337
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c2d6d7'
    - '#697d7b'
    - '#da6600'
    - '#920010'
    - '#181918'
  brandStrength: 0
  lightness: 0.5625
  saturation: 0.375
  rhythmicContrast: 0
purpose:
  - name: null
    item: null
    url: null
