analytics: {}
color:
  brandColors:
    - '#CDCD9C'
    - '#5A6229'
    - '#8B9462'
    - '#E64131'
    - '#EE6A52'
  brandStrength: 1
  lightness: 0.953828
  rhythmicContrast: 0.19375
  saturation: 0.781531
cta: {}
layout_spectrum: 0.8
name: Hannes
opengraph: {}
purpose:
  - {}
