typography_spectrum: 1
color:
  brandColors:
    - '#001D1F'
    - '#E6D3AB'
    - '#FDFDFD'
    - '#BEAF88'
    - '#2F5D5D'
  brandStrength: 0
  lightness: 0.495614
  saturation: 0.375
  rhythmicContrast: 0
opengraph: {}
layout_spectrum: 0.92919
analytics: {}
name: Hannes
cta: {}
style: the-composer
navigation:
  - name: a
    url: h
    type: external
  - name: b
    url: gvb
    type: external
  - name: yo dude
    id: 1cf4d8c7-2d98-4293-907d-d7ddd17b2aa0
    type: content
  - name: d
    url: dhdhd
    type: external
purpose:
  - {}
