analytics: {}
color:
  brandColors:
    - '#0'
    - '#615B23'
    - '#0'
    - '#D5CD8B'
    - '#FFF6AC'
  brandStrength: 1
  lightness: 0.953828
  rhythmicContrast: 0.19375
  saturation: 0.781531
cta: {}
layout_spectrum: 0.8
name: Hannes
opengraph: {}
purpose:
  - {}
