analytics: {}
color:
  brandColors:
    - '#c8c7c5'
    - '#656668'
    - '#2a2e2f'
    - '#a31513'
    - '#fdfefe'
  brandStrength: 0.065315
  lightness: 0.953828
  rhythmicContrast: 0.19375
  saturation: 0.781531
cta: {}
name: Hannes
opengraph: {}
purpose: {}
