analytics: {}
color:
  brandColors:
    - '#BDBDBD'
    - '#101829'
    - '#AC627B'
    - '#486BB7'
    - '#000000'
  brandStrength: 0
  lightness: 0.496621
  rhythmicContrast: 0.820945
  saturation: 1
cta: {}
layout_spectrum: 0.65646
name: Hannes
opengraph: {}
purpose:
  - {}
typography_spectrum: 0.400337
