analytics: {}
color:
  brandColors:
    - '#BDBDBD'
    - '#101829'
    - '#AC627B'
    - '#486BB7'
    - '#000000'
  brandStrength: 0.385135
  lightness: 0.131756
  rhythmicContrast: 0.820945
  saturation: 0.758445
cta: {}
layout_spectrum: 0.464527
name: Hannes
opengraph: {}
purpose:
  - {}
typography_spectrum: 0.400337
